// Copyright 2019 by Utsho Momen

#ifndef  MODULES_PRIME_NUMBER_INCLUDE_PRIMENUMBER_H_
#define  MODULES_PRIME_NUMBER_INCLUDE_PRIMENUMBER_H_

int PrimeNumber(int n);


#endif // MODULES_PRIME_NUMBER_INCLUDE_PRIMENUMBER_H_
